### ISSUE TITLE
Can't resize all elements

### ISSUE THREAD

**Issue by variadico** [nathanielw/Android-Lollipop-Pencil-Stencils#8]
I can resize the floating action button, but not the phone or switch components. I'm on a 13-inch MacBook Air and the phone component doesn't fit on the canvas.

**Comment by nathanielw** [comment]
Thanks for reporting this. Making components resizeable is a bit more work, so I initially left it out, as I wasn't sure how useful it'd be for things like switches. I've just gone through an modified most of the elements to support resizing. The keyboard is the main one that still doesn't scale at all - because it's made up of so many elements, it'd be pretty complex to get it resizing nicely.

Push and new release coming in soon.

edit: Oh, and if the components aren't fitting on the canvas, you can double-click the page tab and adjust the canvas dimensions.

**Comment by variadico** [comment]
Sweet! Thanks!!!
